apiVersion: v1
appVersion: "v1.4.2"
description: A Helm chart for Kubernetes
name: prometheus-msteams
home: https://github.com/prometheus-msteams/prometheus-msteams
version: 1.0.2
maintainers:
  - name: bzon
    url: https://github.com/bzon
  - name: Knappek
    url: https://github.com/Knappek
