apiVersion: v1
appVersion: "v1.5.1"
description: A Helm chart for Kubernetes
name: prometheus-msteams
home: https://github.com/prometheus-msteams/prometheus-msteams
version: 1.3.1
maintainers:
  - name: bzon
    url: https://github.com/bzon
  - name: Knappek
    url: https://github.com/Knappek
