---
replicaCount: 1

image:
  repository: quay.io/prometheusmsteams/prometheus-msteams
  tag: v1.5.2
  pullPolicy: Always

imagePullSecrets: []

extraEnvs: {}

container:
  port: 2000
  additionalArgs: []

resources: {}
#  limits:
#    cpu: 10m
#    memory: 32Mi
#  requests:
#    cpu: 1m
#    memory: 8Mi

service:
  type: ClusterIP
  port: 2000

nodeSelector: {}

tolerations: []

affinity: {}

containerSecurityContext: {}

podSecurityContext:
  runAsUser: 1000
  runAsNonRoot: true

priorityClassName: ""

# Custom labels for pod assignment
podLabels: {}

metrics:
  serviceMonitor:
    enabled: false
    additionalLabels: {}
    scrapeInterval: 30s

## Specify the custom message card template for MS teams
customCardTemplate: ""
# customCardTemplate: |
#   {{ define "teams.card" }}
#   {...}
#   {{ end }}

templateFile: /etc/template/card.tmpl

extraConfigmapMounts: []
# extraConfigmapMounts:
#   - name: customConfigMap
#     configMap:
#       name: customConfigMapName

## Additional Volume mounts
extraVolumeMounts: []
# extraVolumeMounts:
#   - name: volume-name
#     mountPath: /etc/custom_path

connectors: []

# ref: https://github.com/prometheus-msteams/prometheus-msteams#customise-messages-per-ms-teams-channel
connectorsWithCustomTemplates: []
# - request_path: /alert2
#   template_file: |
#     {{ define "teams.card" }}
#     {...}
#     {{ end }}
#   webhook_url: <webhook>
#   escape_underscores: true

# Env from existing secrets or configmaps (in same namespace), will passed through to contains 'envFrom'
envFrom: {}
# envFrom:
#   - secretRef:
#       name: my-prometheus-msteams-env-secret
#   - configMapRef:
#       name: my-prometheus-msteams-env-cm

# Allows overriding the deployment's volume used for providing the config file.
# Can be any valid k8s volume spec but without the "name". E.g. it could be a Secret rather
# than a ConfigMap.
# The volume being mounted must result in a file called "connectors.yaml" being available
# when mounted into the container.
configVolume: {}
# secret:
#   secretName: my-secret-with-config
