---
apiVersion: v1
kind: ConfigMap
metadata:
 name: {{ template "app.name" . }}-config
data:
  connectors.yaml: |
    {{- with $.Values.connectors }}
    connectors:
{{ toYaml . | indent 6 }}
    {{- end}}
