name: Release Docker

on:
  push:
    tags: 
      - 'v*.*.*'
    branches:
      - 'master'

env:
  REGISTRY: quay.io
  IMAGE_NAME: prometheusmsteams/prometheus-msteams
  
jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_QUAY_USER }}
          password: ${{ secrets.DOCKER_QUAY_TOKEN }}

# build

      - name: Build binaries
        id: build-binary
        run: |
          make all

      - name: Build Docker image
        id: build-docker
        uses: docker/build-push-action@v6
        with:
          context: .
          load: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

# tests

      - name: Run tests
        id: test-binary
        run: |
          make test

      - name: Test docker image
        id: test-docker
        # kudos: https://stackoverflow.com/questions/63641822/run-command-with-timeout-in-github-workflow/63643845?noredirect=1#comment112574154_63643845
        # keep docker image running for 2 minutes. It should timeout (error code 124).
        run: | 
          timeout 120 docker run --rm $(echo ${{ steps.meta.outputs.tags }}|head -n1) || code=$?
          if [[ $code -ne 124 ]]; then
            echo "Docker image stopped with ${code}. It was expected to run forever." 
            exit 1;
          fi

# deploy releases

      - name: Create github release
        id: github-release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          fail_on_unmatched_files: true
          generate_release_notes: true
          files: |
            default-message-card.tmpl
            bin/prometheus-msteams-darwin-amd64
            bin/prometheus-msteams-linux-amd64
            bin/prometheus-msteams-windows-amd64.exe
            bin/shasum256.txt

      - name: Push docker image
        id: push-docker
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}